name: CI

on: ["push", "pull_request"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code so GitHub Actions can access it
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Set up Node
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies (includes Vitest)
      - name: Install dependencies
        run: npm install

      # 4. Run test suite
      - name: Run tests
        run: npm run test
